/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "UrlReputationStore";
	}
	interface Env {
		ADMIN_EMAIL?: string;
		AI: Ai;
		BROWSER: import("@cloudflare/puppeteer").BrowserWorker;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		UrlReputationStore: DurableObjectNamespace<import("./src/server").UrlReputationStore>;
		PHISHGUARD_ENRICHMENT: Workflow<import("./src/workflow").EnrichmentParams>;
	}
}
interface Env extends Cloudflare.Env {}
